### PR TITLE
Header

### PR DESCRIPTION
**Pull request by fescii**
Added alt header, without the initial bosstrap library, most text are dummy text and can be replaced

### CODE REVIEW

**Comment by Chal13W1zz** [comment]
I don't see the need for both favicon and boxicons , can we just stick to one?

**Review by pwnipc — APPROVED** [review]
@fescii  your changes have been pushed to the [staging branch](https://github.com/teau-ict-club/club-website/tree/staging), you need to change the following 
 -  congrats on the revamped header design and the creative logo 👏, it looks fantastic but the links are broken☹️
 -  the fontawesome and box icon libraries load up way too many unused icons and images, this has actually made the project grow as big as 400Mb+ I'd recommend the use of only the necessary icons or the web-based URL implementation instead

**Comment by fescii** [comment]
> @fescii your changes have been pushed to the [staging branch](https://github.com/teau-ict-club/club-website/tree/staging), you need to change the following
> 
> * congrats on the revamped header design and the creative logo clap, it looks fantastic but the links are brokenfrowning_face
> * the fontawesome and box icon libraries load up way too many unused icons and images, this has actually made the project grow as big as 400Mb+ I'd recommend the use of only the necessary icons or the web-based URL implementation instead

Great On It

**Comment by fescii** [comment]
> > @fescii your changes have been pushed to the [staging branch](https://github.com/teau-ict-club/club-website/tree/staging), you need to change the following
> > 
> > * congrats on the revamped header design and the creative logo clap, it looks fantastic but the links are brokenfrowning_face
> > * the fontawesome and box icon libraries load up way too many unused icons and images, this has actually made the project grow as big as 400Mb+ I'd recommend the use of only the necessary icons or the web-based URL implementation instead
> 
> Great On It, Initially I'd not inserted any links, let me explore the main repo to get the URLs. I can remove the pro folder then use CDN instead for icons

**Comment by pwnipc** [comment]
> > > @fescii your changes have been pushed to the [staging branch](https://github.com/teau-ict-club/club-website/tree/staging), you need to change the following
> > > 
> > > * congrats on the revamped header design and the creative logo clap, it looks fantastic but the links are brokenfrowning_face
> > > * the fontawesome and box icon libraries load up way too many unused icons and images, this has actually made the project grow as big as 400Mb+ I'd recommend the use of only the necessary icons or the web-based URL implementation instead
> > 
> > 
> > Great On It, Initially I'd not inserted any links, let me explore the main repo to get the URLs. I can remove the pro folder then use CDN instead for icons

That's quite effective actually

**Pull request merged**
